
#################################
security:
    image: busybox
    environment:
        POSTGRES_USER: myadmin
        POSTGRES_PASSWORD: HverYsecretpw
        POSTGRES_DB: docker

#################################
sqldata:
    image: busybox
    volumes:
        - /var/lib/postgresql/data
## Boot2docker bug: http://j.mp/1FMm5qj
#         - ../data/psgr:/var/lib/postgresql/data
#     user: "999"
#     #command: /bin/sh -c "cd /var/lib; mkdir postgresql; chown 999:999 postgresql"

sql:
    image: postgres:9.4
    volumes:
        # Init file && Access security
        - ./init/pginit.sh:/docker-entrypoint-initdb.d/setup-my-schema.sh
    extends:
        service: security
    volumes_from:
        - sqldata
# Note: how to reload config
# $ /usr/lib/postgresql/9.4/bin/pg_ctl reload

#################################
admins:
    image: clue/adminer
    links:
        - sql:db
    ports:
        - 8080:80

#################################
uploads:
    image: busybox
    volumes:
        - /uploads

web:
    image: pdonorio/flasking
    hostname: flask
    command: sleep 1234567890 # DEBUG!
    #command: ./run.py
    #command: gunicorn -b 0.0.0.0:5000 -w2 run:app
    #command: ./bootstrap.sh
    # extends:
    #     service: security
    links:
        - sql:db
    volumes:
        - .:/data:ro
    volumes_from:
        - uploads
    # Open your browser here
    ports:
        - 80:5000
