
sqlsecurity:
    image: busybox
    environment:
        POSTGRES_USER: myadmin
        POSTGRES_PASSWORD: averYsecretpw

#################################
# sqldata:
#     image: busybox
#     command: /bin/sh -c "cd /var/lib; mkdir postgresql; chown 999:999 postgresql"
#     # volumes:
#     #     # Boot2docker bug: http://j.mp/1FMm5qj
#     #     - ../data/psgr:/var/lib/postgresql/data

sql:
    image: postgres
    volumes:
        # Init file && Access security
        - ./init/pginit.sh:/docker-entrypoint-initdb.d/setup-my-schema.sh
    extends:
        #file: common-services.yml
        service: sqlsecurity
#     # /usr/lib/postgresql/9.4/bin/pg_ctl reload
#     volumes_from:
#         - providerdata

#################################
web:
    image: pdonorio/flasking
    hostname: flask
    command: sleep 1234567890
    links:
        - sql:db
    extends:
        service: sqlsecurity
    volumes:
        - ./tests:/data:ro
    working-dir: "/data"
