
#################################
# sqldata:
#     image: busybox
#     command: /bin/sh -c "cd /var/lib; mkdir postgresql; chown 999:999 postgresql"
#     # volumes:
#     #     # Boot2docker bug: http://j.mp/1FMm5qj
#     #     - ../data/psgr:/var/lib/postgresql/data

sql:
    image: postgres
#     # /usr/lib/postgresql/9.4/bin/pg_ctl reload
    environment:
        POSTGRES_USER: myadmin
        POSTGRES_PASSWORD: averYsecretpw
#     volumes_from:
#         - providerdata
    volumes:
        # Init file && Access security
        - ./init/pginit.sh:/docker-entrypoint-initdb.d/setup-my-schema.sh

#################################
web:
    image: pdonorio/flasking
    hostname: flask
    command: sleep 1234567890
    links:
        - sql:db
